/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */

/** Faces that block first paint, in the order they should be requested. */
export const FONT_PRELOADS = [
  '/fonts/bigshoulders.203dd8ba.woff2',
  '/fonts/archivo.7150c0ec.woff2',
] as const;
