/**
 * Downloads the latin subset of each self-hosted face into public/fonts/ and
 * writes src/styles/fonts.css and src/lib/fonts.ts.
 *
 * Fonts are self-hosted because a font from another origin would be a route
 * data could leave by, and would force an extra host into the CSP.
 *
 * All three families are variable, so each is downloaded ONCE and declared with
 * a weight range; requesting named weights returns the same bytes three times.
 *
 * Filenames carry a content hash, which is what lets public/_headers hold them
 * for a year as `immutable`. They used to be stable names on a one-day cache,
 * so every visitor spent a round trip revalidating a render-blocking preload
 * that had not changed since the site was built. Different bytes now mean a
 * different name, so there is nothing to revalidate and nothing to go stale.
 *
 * The licence is fetched too, and a bad response fails the script rather than
 * being written — shipping an error page as a font licence would be worse.
 */
import { createHash } from 'node:crypto';
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fontDir = join(root, 'public', 'fonts');

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

/**
 * `preload` marks the faces that draw the first paint — the display face used
 * by every heading and the body face under it. JetBrains Mono is deliberately
 * absent: it appears inside the tools, by which point it has long since
 * arrived, and preloading it would compete with the two that are visible
 * immediately.
 */
const FACES = [
  {
    family: 'Big Shoulders Display',
    slug: 'bigshoulders',
    axis: 'wght@100..900',
    weights: '100 900',
    preload: true,
    copyright:
      'Copyright The Big Shoulders Project Authors (https://github.com/xotypeco/big_shoulders)',
  },
  {
    family: 'Archivo',
    slug: 'archivo',
    axis: 'wght@100..900',
    weights: '100 900',
    preload: true,
    copyright: 'Copyright The Archivo Project Authors (https://github.com/Omnibus-Type/Archivo)',
  },
  {
    family: 'JetBrains Mono',
    slug: 'jetbrainsmono',
    axis: 'wght@100..800',
    weights: '100 800',
    preload: false,
    copyright:
      'Copyright The JetBrains Mono Project Authors (https://github.com/JetBrains/JetBrainsMono)',
  },
];

const LICENCE_SOURCE = 'https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/OFL.txt';

/** Keep only the block whose unicode-range covers basic latin. */
function latinBlocks(css) {
  return [...css.matchAll(/@font-face\s*\{([^}]+)\}/g)]
    .map((match) => match[1])
    .filter((block) => /unicode-range:[^;]*U\+0000-00FF/.test(block));
}

function field(block, name) {
  const match = block.match(new RegExp(`${name}:\\s*([^;]+);`));
  return match ? match[1].trim() : '';
}

await mkdir(fontDir, { recursive: true });
const rules = [];
/** @type {string[]} */
const preloads = [];
/** Names written this run. Anything else with a .woff2 extension is a previous hash. */
const written = new Set();

for (const face of FACES) {
  const spec = `${face.family.replace(/ /g, '+')}:${face.axis}`;
  const css = await fetch(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, {
    headers: { 'User-Agent': UA },
  }).then((response) => response.text());

  const [block] = latinBlocks(css);
  if (!block) throw new Error(`No latin subset returned for ${face.family}`);

  const url = field(block, 'src').match(/url\((https:[^)]+)\)/)?.[1];
  if (!url) throw new Error(`No font URL for ${face.family}`);

  const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8);
  const filename = `${face.slug}.${hash}.woff2`;
  await writeFile(join(fontDir, filename), bytes);
  written.add(filename);
  if (face.preload) preloads.push(`/fonts/${filename}`);
  console.log(`  ${filename}  ${(bytes.length / 1024).toFixed(1)} KB  (weights ${face.weights})`);

  rules.push(
    `@font-face {\n  font-family: '${face.family}';\n  font-style: normal;\n  font-weight: ${face.weights};\n  font-display: swap;\n  src: url('/fonts/${filename}') format('woff2');\n  unicode-range: ${field(block, 'unicode-range')};\n}`,
  );
}

/* Hashed names accumulate: a refresh that changes one face leaves the old one
   in public/, from where it would ship in the next build forever. Nothing
   references it, so removing it is safe — and not removing it means the repo
   grows a font per upstream release. */
for (const name of await readdir(fontDir)) {
  if (name.endsWith('.woff2') && !written.has(name)) {
    await rm(join(fontDir, name));
    console.log(`  removed ${name} (superseded)`);
  }
}

await writeFile(
  join(root, 'src', 'styles', 'fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n   Self-hosted so the site never requests a third-party origin.\n   One variable file per family; see public/fonts/OFL.txt for licensing. */\n\n${rules.join('\n\n')}\n`,
);

/* The filenames now change with their contents, so the two places that name
   them — the <head> preloads and the Link: header that feeds Early Hints —
   cannot hold a literal. Both read this. */
await writeFile(
  join(root, 'src', 'lib', 'fonts.ts'),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n/** Faces that block first paint, in the order they should be requested. */\nexport const FONT_PRELOADS = [\n${preloads
    .map((path) => `  '${path}',\n`)
    .join('')}] as const;\n`,
);

const licence = await fetch(LICENCE_SOURCE).then((response) => response.text());
if (!licence.includes('SIL OPEN FONT LICENSE')) {
  throw new Error(`Licence fetch did not return OFL text (got ${licence.length} bytes)`);
}

await writeFile(
  join(fontDir, 'OFL.txt'),
  `The fonts in this directory are licensed under the SIL Open Font License 1.1.\n\n${FACES.map(
    (face) => `${face.family}\n  ${face.copyright}`,
  ).join('\n\n')}\n\nThe full licence text follows.\n\n${'='.repeat(72)}\n\n${licence}`,
);
console.log(`  OFL.txt  ${(licence.length / 1024).toFixed(1)} KB`);

console.log(`\nWrote src/styles/fonts.css with ${rules.length} faces.`);
