/**
 * Downloads the latin subset of each self-hosted face into public/fonts/ and
 * writes src/styles/fonts.css.
 *
 * Fonts are self-hosted because the site forbids third-party requests: a
 * stylesheet or font pulled from another origin would be a route data could
 * leave by, and would force an extra host into the CSP.
 *
 * All three families ship as variable fonts, so each is downloaded ONCE and
 * declared with a weight range. Requesting named weights returns the same bytes
 * under different filenames — three downloads of one file.
 *
 * The licence text is fetched too, and the script fails loudly rather than
 * writing whatever came back: a site claiming auditability must not ship an
 * error page as its font licence.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fontDir = join(root, 'public', 'fonts');

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FACES = [
  {
    family: 'Big Shoulders Display',
    slug: 'bigshoulders',
    axis: 'wght@100..900',
    weights: '100 900',
    copyright:
      'Copyright The Big Shoulders Project Authors (https://github.com/xotypeco/big_shoulders)',
  },
  {
    family: 'Archivo',
    slug: 'archivo',
    axis: 'wght@100..900',
    weights: '100 900',
    copyright: 'Copyright The Archivo Project Authors (https://github.com/Omnibus-Type/Archivo)',
  },
  {
    family: 'JetBrains Mono',
    slug: 'jetbrainsmono',
    axis: 'wght@100..800',
    weights: '100 800',
    copyright:
      'Copyright The JetBrains Mono Project Authors (https://github.com/JetBrains/JetBrainsMono)',
  },
];

const LICENCE_SOURCE = 'https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/OFL.txt';

/** Keep only the block whose unicode-range covers basic latin. */
function latinBlocks(css) {
  return [...css.matchAll(/@font-face\s*\{([^}]+)\}/g)]
    .map((match) => match[1])
    .filter((block) => /unicode-range:[^;]*U\+0000-00FF/.test(block));
}

function field(block, name) {
  const match = block.match(new RegExp(`${name}:\\s*([^;]+);`));
  return match ? match[1].trim() : '';
}

await mkdir(fontDir, { recursive: true });
const rules = [];

for (const face of FACES) {
  const spec = `${face.family.replace(/ /g, '+')}:${face.axis}`;
  const css = await fetch(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, {
    headers: { 'User-Agent': UA },
  }).then((response) => response.text());

  const [block] = latinBlocks(css);
  if (!block) throw new Error(`No latin subset returned for ${face.family}`);

  const url = field(block, 'src').match(/url\((https:[^)]+)\)/)?.[1];
  if (!url) throw new Error(`No font URL for ${face.family}`);

  const filename = `${face.slug}.woff2`;
  const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
  await writeFile(join(fontDir, filename), bytes);
  console.log(`  ${filename}  ${(bytes.length / 1024).toFixed(1)} KB  (weights ${face.weights})`);

  rules.push(
    `@font-face {\n  font-family: '${face.family}';\n  font-style: normal;\n  font-weight: ${face.weights};\n  font-display: swap;\n  src: url('/fonts/${filename}') format('woff2');\n  unicode-range: ${field(block, 'unicode-range')};\n}`,
  );
}

await writeFile(
  join(root, 'src', 'styles', 'fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n   Self-hosted so the site never requests a third-party origin.\n   One variable file per family; see public/fonts/OFL.txt for licensing. */\n\n${rules.join('\n\n')}\n`,
);

const licence = await fetch(LICENCE_SOURCE).then((response) => response.text());
if (!licence.includes('SIL OPEN FONT LICENSE')) {
  throw new Error(`Licence fetch did not return OFL text (got ${licence.length} bytes)`);
}

await writeFile(
  join(fontDir, 'OFL.txt'),
  `The fonts in this directory are licensed under the SIL Open Font License 1.1.\n\n${FACES.map(
    (face) => `${face.family}\n  ${face.copyright}`,
  ).join('\n\n')}\n\nThe full licence text follows.\n\n${'='.repeat(72)}\n\n${licence}`,
);
console.log(`  OFL.txt  ${(licence.length / 1024).toFixed(1)} KB`);

console.log(`\nWrote src/styles/fonts.css with ${rules.length} faces.`);
